#source: "Face detection.mp4"
source: "/home/maksym/Downloads/P1E_S1/P1E_S1_C2_FILLED/%08d.jpg"
source_scale: 1
face_buffer_size: 20
face_shape: [60, 60]

database:
  kind: memory

face_encoder:
  name: dlib_encoder
  params:
    path_to_cnn_model: face/files/dlib_face_recognition_resnet_model_v1.dat
    path_to_landmark_model: face/files/shape_predictor_5_face_landmarks.dat

face_recognizer:
  name: dlib_recognizer
  params:
    threshold: 0.6

face_detector:
#  name: "hog_detector"
#  params:
#    threshold: 0.5
  name: cascade_detector
  params:
    path_to_xml: face/files/haarcascade_frontalface_default.xml
    scale_factor: 1.2
    min_neighbour: 21

face_tracker:
  name: mil_tracker
  params:
    trace_len: 10

face_validators:
  -
    name: min_box_size_validator
    params:
      min_width: 50
      min_height: 50
  -
    name: same_detection_validator
    params:
      max_iou: 0.2
#  -
#    name: fft_blur_validator
#    params:
#      kernel_size: 50
#      threshold: 25
#  -
#    name: laplace_blur_validator
#    params:
#      threshold: 0.03

frame_filters:
  - name: fake_filter
